I had issues running Editor.class
~$ java Editor

Error: Could not find or load main class Editor
Caused by: java.lang.NoClassDefFoundError: editor/Editor (wrong name: Editor)